apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    app: grafana
---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  service: {}
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "admin"
      admin_password: "admin"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
    - matchExpressions:
        - {key: grafana, operator: In, values: [dashabord]}
---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: grafana
spec:
  type: ClusterIP
  ports:
    - name: grafana
      protocol: TCP
      port: 80
      targetPort: grafana-http
  selector:
    app: grafana
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: grafana
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.${INGRESS_DOMAIN}
    http:
      paths:
      - backend:
          service:
            name: grafana
            port: 
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
  labels:
    app: grafana
  namespace: grafana
spec:
  name: prometheus.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.prometheus.svc:80
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
