apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: strimzi-operators
  labels:
    app: grafana
    grafana: dashabord
  namespace: grafana
spec:
  json: ""
  url: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/${STRIMZI_VERSION}/examples/metrics/grafana-dashboards/strimzi-operators.json
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "Prometheus"
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata: 
  name: strimzi-kafka
  labels:
    app: grafana
    grafana: dashabord
  namespace: grafana
spec:
  json: ""
  url: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/${STRIMZI_VERSION}/packaging/examples/metrics/strimzi-metrics-reporter/grafana-dashboards/strimzi-kafka.json
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "Prometheus"
