apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: add-brokers
  labels:
    # must match the cluster name
    strimzi.io/cluster: my-cluster
spec:
  # using default goals
  mode: add-brokers
  brokers: [3]
