apiVersion: kafka.strimzi.io/v1
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
spec:
  replicas: 1
  #version: x.y.z
  target:
    alias: my-cluster-tgt
    bootstrapServers: my-cluster-tgt-kafka-bootstrap.${TARGET_NS}.svc:9093
    groupId: my-mm2-cluster
    configStorageTopic: my-mm2-config
    statusStorageTopic: my-mm2-status
    offsetStorageTopic: my-mm2-offset
    tls:
      trustedCertificates:
        - certificate: ca.crt
          secretName: my-cluster-tgt-cluster-ca-cert
    config:
      # -1 means use default broker RF
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
    - source:
        alias: my-cluster
        bootstrapServers: my-cluster-kafka-bootstrap.${SOURCE_NS}.svc:9093
        tls:
          trustedCertificates:
            - certificate: ca.crt
              secretName: my-cluster-cluster-ca-cert
      topicsPattern: ".*"
      groupsPattern: ".*"
      sourceConnector:
        tasksMax: 10
        config:
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          offset-syncs.topic.location: target
          key.converter: "org.apache.kafka.connect.converters.ByteArrayConverter"
          value.converter: "org.apache.kafka.connect.converters.ByteArrayConverter"
          # disable source cluster name prefix on target topic
          replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
          refresh.topics.interval.seconds: 20
          sync.topic.configs.enabled: true
          sync.topic.acls.enabled: false
      checkpointConnector:
        tasksMax: 10
        config:
          checkpoints.topic.replication.factor: -1
          key.converter: "org.apache.kafka.connect.converters.ByteArrayConverter"
          value.converter: "org.apache.kafka.connect.converters.ByteArrayConverter"
          # disable source cluster name prefix on target topic
          replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
          sync.group.offsets.enabled: true
          sync.group.offsets.interval.seconds: 20
          emit.checkpoints.enabled: true
          emit.checkpoints.interval.seconds: 20
          refresh.groups.interval.seconds: 20
  logging:
    type: inline
    loggers:
      rootLogger.level: INFO
      logger.source.name: org.apache.kafka.connect.runtime.WorkerSourceTask
      logger.source.level: INFO
      logger.sink.name: org.apache.kafka.connect.runtime.WorkerSinkTask
      logger.sink.level: INFO
  resources:
    requests:
      cpu: 2000m
      memory: 2Gi
  # expose metrics in Prometheus format on port 9404
  metricsConfig:
    type: strimziMetricsReporter
