apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: combined
  labels:
    # must match the cluster name
    strimzi.io/cluster: my-cluster-tgt
spec:
  replicas: 3
  roles:
    - controller
    - broker
  resources:
    # set requests==limits to have Guaranteed QoS
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
  storage:
    size: 5Gi
    type: persistent-claim
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster-tgt
spec:
  kafka:
    config:
      num.partitions: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
