apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    # must match the cluster name
    strimzi.io/cluster: my-cluster
  annotations:
    strimzi.io/next-node-ids: "[0-9]"
spec:
  replicas: 3
  roles:
    - controller
  resources:
    # set requests==limits to have Guaranteed QoS
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  storage:
    size: 5Gi
    type: persistent-claim
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    # must match the cluster name
    strimzi.io/cluster: my-cluster
  annotations:
    strimzi.io/next-node-ids: "[10-100]"
spec:
  replicas: 3
  roles:
    - broker
  resources:
    # set requests==limits to have Guaranteed QoS
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi
  storage:
    size: 10Gi
    type: persistent-claim
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    #version: x.y.z
    #metadataVersion: x.y-IVz
    config:
      num.partitions: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    logging:
      type: inline
      loggers:
        rootLogger.level: INFO
        logger.kafka.request.logger.level: INFO
        logger.kafkatc.name: kafka.coordinator.transaction
        logger.kafkatc.level: INFO
        logger.kafkalcm.name: kafka.log.LogCleanerManager
        logger.kafkalcm.level: INFO
        logger.strimzi.name: io.strimzi
        logger.strimzi.level: INFO
    metricsConfig:
      type: strimziMetricsReporter
  entityOperator:
    topicOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
          logger.top.name: io.strimzi.operator.topic
          logger.top.level: INFO
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 256Mi
    userOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
          logger.uop.name: io.strimzi.operator.user
          logger.uop.level: INFO
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 256Mi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    # must match the cluster name
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    min.insync.replicas: 2
    # 1 GiB to avoid running out of space with load tests
    retention.bytes: 1073741824
