apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-connect-mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-connect-mysql-cfg
data:
  # the server_id must be unique for each server or replication client
  my.cnf: |
    !include /etc/my.cnf
    [mysqld]
    server_id = 111111
    log_bin = mysql-bin
    binlog_format = ROW
    binlog_row_image = FULL
    binlog_rows_query_log_events = ON
    expire_logs_days = 10
    gtid_mode = ON
    enforce_gtid_consistency = ON
---
apiVersion: v1
kind: Secret
metadata:
  name: my-connect-mysql-env
type: Opaque
stringData:
  MYSQL_DEFAULTS_FILE: /config/configdb.d/my.cnf
  MYSQL_DATABASE: testdb
  MYSQL_USER: admin
  MYSQL_PASSWORD: changeit
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-connect-mysql-init
data:
  initdb.sql: |
    use testdb;
    CREATE TABLE customers (
      id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
      first_name VARCHAR(255) NOT NULL,
      last_name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE
    );

    CREATE USER IF NOT EXISTS 'debezium'@'%' IDENTIFIED WITH caching_sha2_password BY 'changeit';
    GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'debezium'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-connect-mysql
spec:
  replicas: 1
  serviceName: my-connect-mysql
  selector:
    matchLabels:
      app: my-connect-mysql
  template:
    metadata:
      labels:
        app: my-connect-mysql
    spec:
      containers:
        - name: mysql
          image: registry.redhat.io/rhscl/mysql-80-rhel7:8.0
          resources:
            limits:
              memory: 1Gi
          envFrom:
            - secretRef:
                name: my-connect-mysql-env
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: my-connect-mysql-data
              mountPath: /var/lib/mysql
            - name: my-connect-mysql-cfg
              mountPath: /config/configdb.d
            - name: my-connect-mysql-init
              mountPath: /tmp/sql
          readinessProbe:
            exec:
              command: [ "mysqladmin", "-uroot", "ping" ]
            initialDelaySeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: [ "mysqladmin", "-uroot", "ping" ]
            initialDelaySeconds: 60
            timeoutSeconds: 10
      volumes:
        - name: my-connect-mysql-data
          persistentVolumeClaim:
            claimName: my-connect-mysql-data
        - name: my-connect-mysql-cfg
          configMap:
            name: my-connect-mysql-cfg
        - name: my-connect-mysql-init
          configMap:
            name: my-connect-mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: my-connect-mysql-svc
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: my-connect-mysql
---
