apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PVC_NAME
  labels:
    strimzi.io/name: CLUSTER_NAME-kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: NEW_PV_CLASS
  volumeName: NEW_PV_NAME
  resources:
    requests:
      storage: NEW_PV_SIZE
