apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: SED_NAME
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: SED_SIZE
  storageClassName: SED_CLASS
  volumeMode: Filesystem
  volumeName: SED_VOLUME
