apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 3
    version: 3.2.3
    config:
      # lowest protocol version (downgrade is not supported)
      inter.broker.protocol.version: "3.2"
      num.partitions: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: route
        tls: true
        authentication:
          type: tls
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 2Gi
    storage:
      size: 10Gi
      type: persistent-claim
      deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    template:
      pod:
        terminationGracePeriodSeconds: 60
  zookeeper:
    replicas: 3
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    storage:
      size: 5Gi
      type: persistent-claim
      deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
  entityOperator:
    topicOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 256Mi
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
    userOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 256Mi
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 10
